import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowRight, BookOpen, BriefcaseBusiness, Building2, Check, ChevronLeft, ChevronRight, Home, Map, Menu, PanelLeftClose, PanelLeftOpen, Route as RouteIcon, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Feedback, KPIBadge, ProcessFlow, ResetButton, RiskCard, SectionHeading } from "@/components/learning-ui";
import { areas, courseRoute, flow, problemMaps, risks, scenarios } from "@/data/course-content";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title:"AI Business Explorer — IA aplicada a la Gestión Empresarial" },
    { name:"description", content:"Laboratorio educativo interactivo para descubrir cómo la IA genera valor medible en una organización." },
    { property:"og:title", content:"AI Business Explorer — Masterclass" },
    { property:"og:description", content:"Explora problemas, datos, aplicaciones de IA, decisiones humanas e impacto empresarial." },
    { property:"og:type", content:"website" },
    { name:"twitter:card", content:"summary_large_image" },
  ]}), component: Index,
});

const navItems = [
 {id:"inicio",label:"Inicio",icon:Home},
 {id:"explorar",label:"Explorar empresa",icon:Building2},
 {id:"simulador",label:"Simulador",icon:Sparkles},
 {id:"nova",label:"Caso NOVA",icon:BriefcaseBusiness},
 {id:"reto",label:"Reto final",icon:Target},
 {id:"ruta",label:"Ruta del curso",icon:RouteIcon},
] as const;
const sectionIds = navItems.map(item=>item.id);

function Index() {
 const [visited,setVisited]=useState(new Set(["inicio"]));
 const [active,setActive]=useState("inicio");
 const [menu,setMenu]=useState(false);
 const [collapsed,setCollapsed]=useState(false);
 useEffect(()=>{ const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){setActive(e.target.id);setVisited(v=>new Set(v).add(e.target.id))}}),{rootMargin:"-20% 0px -65%",threshold:0}); sectionIds.forEach(id=>{const el=document.getElementById(id);if(el)obs.observe(el)}); return()=>obs.disconnect()},[]);
 const go=(id:string)=>{setActive(id);document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)};
 return <div className="min-h-screen overflow-x-hidden bg-background font-display text-foreground selection:bg-accent/30">
   <div className="ambient ambient-a"/><div className="ambient ambient-b"/>
   <Sidebar active={active} visited={visited} collapsed={collapsed} setCollapsed={setCollapsed} go={go}/>
   <MobileHeader visited={visited.size} menu={menu} setMenu={setMenu} active={active} go={go}/>
   <div className={`relative transition-[margin] duration-300 md:${collapsed?"ml-16":"ml-64"}`}>
    <main className="relative z-10">
     <Welcome onStart={()=>go("apertura")}/>
     <Opening onNext={()=>go("modelo")}/>
     <CentralModel/>
     <BusinessExplorer/>
     <BeforeAfter/>
     <Simulator/>
     <ProblemLab/>
     <NovaCase/>
     <HumanAI/>
     <Risks/>
     <FinalChallenge/>
     <Roadmap/>
    </main>
    <Footer/>
   </div>
 </div>
}

function Sidebar({active,visited,collapsed,setCollapsed,go}:{active:string;visited:Set<string>;collapsed:boolean;setCollapsed:(v:boolean)=>void;go:(id:string)=>void}) {
 const progress=Math.round(visited.size/sectionIds.length*100);
 return <aside className={`fixed inset-y-0 left-0 z-50 hidden border-r border-line bg-background/95 backdrop-blur-xl transition-[width] duration-300 md:flex md:flex-col ${collapsed?"w-16":"w-64"}`}>
  <div className="grid h-16 grid-cols-[minmax(0,1fr)_auto] items-center gap-2 border-b border-line px-3">
   <Button variant="ghost" className="min-w-0 justify-start px-1" onClick={()=>go("inicio")} aria-label="Ir al inicio"><span className="grid size-8 shrink-0 place-items-center rounded-md bg-accent font-mono text-xs font-bold text-accent-ink">AI</span>{!collapsed&&<span className="truncate text-xs font-bold uppercase">Business Explorer</span>}</Button>
   {!collapsed&&<Button variant="ghost" size="icon" onClick={()=>setCollapsed(true)} aria-label="Contraer menú lateral" title="Contraer menú"><PanelLeftClose/></Button>}
  </div>
  <div className="border-b border-line px-4 py-4">{collapsed?<Button variant="ghost" size="icon" onClick={()=>setCollapsed(false)} aria-label="Expandir menú lateral" title="Expandir menú"><PanelLeftOpen/></Button>:<><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><span className="font-mono text-[9px] uppercase text-muted-foreground">Progreso</span><span className="font-mono text-[9px] text-accent">{progress}%</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-line"><div className="h-full bg-accent transition-all duration-500" style={{width:`${progress}%`}}/></div><p className="mt-2 text-[10px] text-muted-foreground">{visited.size} de {sectionIds.length} temas explorados</p></>}</div>
  <nav className="flex-1 space-y-1 overflow-y-auto p-2" aria-label="Temas de la masterclass">{navItems.map(({id,label,icon:Icon})=><Button key={id} variant="ghost" onClick={()=>go(id)} aria-current={active===id?"location":undefined} title={collapsed?label:undefined} className={`h-11 w-full ${collapsed?"justify-center px-0":"justify-start px-3"} ${active===id?"bg-accent/10 text-accent":"text-muted-foreground hover:text-foreground"}`}><Icon className="shrink-0"/>{!collapsed&&<span className="truncate">{label}</span>}{!collapsed&&visited.has(id)&&<Check className="ml-auto size-3.5 text-accent"/>}</Button>)}</nav>
  {!collapsed&&<div className="border-t border-line p-4"><span className="inline-flex rounded-full border border-accent/30 bg-accent/10 px-2.5 py-1 font-mono text-[9px] uppercase text-accent">Masterclass</span><p className="mt-3 text-xs leading-relaxed text-muted-foreground">IA aplicada a la Gestión Empresarial</p></div>}
 </aside>
}

function MobileHeader({visited,menu,setMenu,active,go}:{visited:number;menu:boolean;setMenu:(v:boolean)=>void;active:string;go:(id:string)=>void}) {
 const progress=Math.round(visited/sectionIds.length*100);
 return <header className="sticky top-0 z-50 border-b border-line bg-background/90 backdrop-blur-xl md:hidden">
  <div className="grid h-14 grid-cols-[minmax(0,1fr)_auto] items-center gap-3 px-4"><Button variant="ghost" className="min-w-0 justify-start px-0" onClick={()=>go("inicio")}><span className="grid size-8 shrink-0 place-items-center rounded-md bg-accent font-mono text-xs font-bold text-accent-ink">AI</span><span className="truncate text-xs font-bold uppercase">Business Explorer</span></Button><Button variant="outline" size="icon" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?"Cerrar menú":"Abrir menú"}>{menu?<X/>:<Menu/>}</Button></div>
  <div className="h-0.5 bg-line"><div className="h-full bg-accent transition-all duration-500" style={{width:`${progress}%`}}/></div>
  {menu&&<nav className="absolute inset-x-0 top-full grid max-h-[calc(100vh-3.5rem)] gap-1 overflow-y-auto border-b border-line bg-surface p-3 shadow-xl" aria-label="Temas de la masterclass">{navItems.map(({id,label,icon:Icon})=><Button key={id} variant="ghost" onClick={()=>go(id)} className={`h-12 justify-start ${active===id?"bg-accent/10 text-accent":"text-muted-foreground"}`}><Icon/>{label}</Button>)}</nav>}
 </header>
}

function Welcome({onStart}:{onStart:()=>void}) { return <section id="inicio" className="mx-auto grid min-h-[78vh] max-w-[1240px] items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.1fr_.9fr]">
 <div className="rise"><p className="font-mono text-[11px] uppercase tracking-[0.28em] text-accent">Inteligencia Artificial aplicada a la Gestión Empresarial</p><p className="mt-4 text-sm font-semibold uppercase text-muted-foreground">Masterclass</p><h1 className="mt-3 max-w-[14ch] text-balance text-5xl font-black uppercase leading-[.94] sm:text-7xl">La Inteligencia Artificial y el nuevo modelo de gestión empresarial</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground">Descubre cómo la IA transforma problemas empresariales en información, decisiones y resultados.</p><Button size="lg" className="mt-8 h-12 rounded-full px-6 font-bold uppercase" onClick={onStart}>Comenzar exploración<ArrowDown/></Button></div>
 <div className="network" aria-label="Flujo visual de empresa, datos, inteligencia artificial y decisión"><div className="network-core"><Building2 className="size-8"/><strong>EMPRESA</strong></div>{["Datos","IA","Decisión","Impacto"].map((x,i)=><div key={x} className={`network-node node-${i+1}`}><span>0{i+1}</span>{x}</div>)}</div>
 </section> }

function Opening({onNext}:{onNext:()=>void}) { const [reveal,setReveal]=useState(false); const qs=["¿Qué comprar?","¿Cuánto inventario mantener?","¿Qué producto vender?","¿Qué clientes necesitan atención?","¿Dónde aumentan los costos?","¿Qué proveedor elegir?","¿Qué tareas están retrasadas?","¿Qué causa reclamos?","¿Qué campaña funciona mejor?","¿Dónde hay una oportunidad?"]; return <section id="apertura" className="band"><div className="shell text-center"><p className="eyebrow">Pregunta de apertura</p><h2 className="mx-auto mt-3 max-w-3xl text-balance text-3xl font-bold uppercase sm:text-5xl">¿Cuántas decisiones toma una empresa todos los días?</h2><div className="mx-auto mt-10 grid max-w-4xl grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{qs.map((q,i)=><button key={q} onClick={()=>setReveal(true)} className="decision-chip" style={{animationDelay:`${i*50}ms`}}>{q}</button>)}</div>{reveal&&<div className="rise mt-10"><p className="text-balance text-xl text-accent sm:text-2xl">¿Qué ocurriría si pudiéramos analizar más información en menos tiempo?</p><Button className="mt-6 rounded-full" onClick={onNext}>Descubrir el papel de la IA<ArrowDown/></Button></div>}</div></section> }

function CentralModel(){const [active,setActive]=useState(0);return <section id="modelo" className="shell py-20"><SectionHeading eyebrow="Modelo central" title="Del problema empresarial al impacto medible" aside="Selecciona cada etapa para comprender su función."/><div className="mt-8"><ProcessFlow items={flow} interactive active={active} onSelect={setActive}/></div><blockquote className="mt-8 border-l-2 border-accent pl-5 text-xl font-semibold">“Utilizar IA empresarialmente significa aplicarla a un problema para generar valor medible.”</blockquote></section>}

function BusinessExplorer(){const [selected,setSelected]=useState(areas[6] ?? areas[0]);if(!selected)return null;return <section id="explorar" className="band"><div className="shell"><SectionHeading eyebrow="IA Business Explorer" title="¿Dónde puede generar valor la IA?" aside="Selecciona un área y conecta el problema con un indicador concreto."/><div className="mt-8 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{areas.map(a=>{const Icon=a.icon;return <button key={a.id} onClick={()=>setSelected(a)} className={`area-button ${selected.id===a.id?"area-active":""}`}><Icon/><span>{a.name}</span></button>})}</div><article className="glass-panel" aria-live="polite"><div className="flex items-center justify-between"><h3 className="text-2xl font-bold uppercase">{selected.name}</h3><span className="eyebrow">Área activa</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info title="Problemas frecuentes" list={selected.problems}/><Info title="Datos disponibles" list={selected.data}/><Info title="Aplicaciones posibles de IA" list={selected.uses}/><div className="info-box"><span>Ejemplo empresarial</span><p>{selected.example}</p></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-accent/10 p-4"><p><span className="text-xs text-muted-foreground">Beneficio esperado</span><strong className="block">{selected.benefit}</strong></p><KPIBadge>{selected.kpi}</KPIBadge></div></article></div></div></section>}
function Info({title,list}:{title:string;list:string[]}){return <div className="info-box"><span>{title}</span><ul>{list.map(x=><li key={x}>{x}</li>)}</ul></div>}

function BeforeAfter(){const [mode,setMode]=useState<"before"|"after">("after");const before=["500 comentarios","Empleado revisa","Clasifica manualmente","Agrupa problemas","Construye reporte","Gerencia analiza","Decisión"];const after=["500 comentarios","IA analiza","Clasifica, resume y detecta patrones","Responsable valida","Reporte","Gerencia interpreta","Decisión"];return <section className="shell py-20"><SectionHeading eyebrow="Comparador" title="¿Dónde cambia realmente el trabajo?" aside="Ejemplo didáctico · Los tiempos son ilustrativos, no evidencia científica."/><div className="mt-7 flex w-fit rounded-lg border border-line bg-surface p-1"><Button variant={mode==="before"?"default":"ghost"} onClick={()=>setMode("before")}>Proceso tradicional</Button><Button variant={mode==="after"?"default":"ghost"} onClick={()=>setMode("after")}>Apoyado por IA</Button></div><div className="mt-6 glass-panel"><div className="flow-list">{(mode==="before"?before:after).map((x,i)=><div className="contents" key={x}><div className={mode==="after"&&(i===1||i===2)?"flow-step active":"flow-step"}>{x}</div>{i<(mode==="before"?before:after).length-1&&<ArrowRight className="hidden text-muted-foreground md:block"/>}</div>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-3"><span className={mode==="before"?"time-badge warning":"time-badge"}>{mode==="before"?"Tiempo estimado: varias horas":"Más tiempo para interpretar y decidir"}</span><span className="text-sm text-muted-foreground">Caso educativo · Datos simulados</span></div></div><p className="mt-5 max-w-4xl text-lg leading-relaxed">La IA puede reducir el tiempo dedicado a procesar información y permitir que las personas dediquen más tiempo a interpretar, validar y decidir.</p></section>}

function Simulator(){const [idx,setIdx]=useState(0);const [answer,setAnswer]=useState<number>();const s=scenarios[idx] ?? scenarios[0];if(!s)return null;const choose=(i:number)=>setAnswer(i);return <section id="simulador" className="band"><div className="shell"><SectionHeading eyebrow={`Simulador · escenario ${idx+1} de ${scenarios.length}`} title="¿Dónde usarías IA?" aside="Analiza el problema antes de elegir una aplicación."/><div className="mt-8 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="glass-panel"><span className="eyebrow">{s.area} · Caso educativo</span><p className="mt-4 text-xl font-semibold leading-relaxed">{s.situation}</p></div><div className="glass-panel"><div className="grid gap-2">{s.options.map((o,i)=><button key={o} onClick={()=>choose(i)} className={`option ${answer===i?(i===s.correct?"correct":"selected"):""}`}><span>{String.fromCharCode(65+i)}</span>{o}{answer===i&&i===s.correct&&<Check className="ml-auto"/>}</button>)}</div>{answer!==undefined&&<><Feedback correct={answer===s.correct}>{answer===s.correct?s.explanation:`Esta opción no aborda el problema con suficiente control. ${s.explanation}`}</Feedback><MiniChain items={s.chain}/></>}<div className="mt-5 flex items-center justify-between"><Button variant="ghost" disabled={idx===0} onClick={()=>{setIdx(idx-1);setAnswer(undefined)}}><ChevronLeft/>Anterior</Button><span className="font-mono text-xs text-muted-foreground">{idx+1} / {scenarios.length}</span><Button variant="outline" disabled={idx===scenarios.length-1} onClick={()=>{setIdx(idx+1);setAnswer(undefined)}}>Siguiente<ChevronRight/></Button></div></div></div></div></section>}
function MiniChain({items}:{items:string[]}){return <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{["Problema","Datos","IA","Resultado","Decisión humana","KPI"].map((x,i)=><div className="rounded-md bg-surface p-2.5" key={x}><span className="font-mono text-[9px] uppercase text-accent">{x}</span><p className="mt-1 text-xs">{items[i]}</p></div>)}</div>}

function ProblemLab(){const [sel,setSel]=useState(0);const item=problemMaps[sel] ?? problemMaps[0];if(!item)return null;return <section className="shell py-20"><SectionHeading eyebrow="Laboratorio problema → valor" title="Empieza por el problema, no por la herramienta" aside="Selecciona una necesidad empresarial para construir la cadena de valor."/><div className="mt-8 grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><div className="grid grid-cols-2 gap-2">{problemMaps.map((p,i)=><button key={p[0]} onClick={()=>setSel(i)} className={`problem-button ${sel===i?"active":""}`}>{p[0]}</button>)}</div><div className="glass-panel"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{["Problema","Información necesaria","Posible uso de IA","Resultado","Decisión","KPI"].map((x,i)=><div className="info-box" key={x}><span>{x}</span><p>{item[i]}</p></div>)}</div></div></div><div className="mt-8 rounded-lg border border-amber/30 bg-amber/10 p-5 text-center"><p className="text-sm text-muted-foreground line-through">¿Qué IA puedo utilizar?</p><p className="mt-2 text-xl font-bold text-amber">¿Qué problema empresarial quiero resolver?</p></div></section>}

const novaItems=[{name:"Atención al cliente",x:68,y:82},{name:"Inventarios",x:45,y:90},{name:"Reportes",x:88,y:64},{name:"Correos",x:92,y:76},{name:"Ventas",x:55,y:70}];
function NovaCase(){const [choice,setChoice]=useState("");const [matrix,setMatrix]=useState(false);return <section id="nova" className="band"><div className="shell"><SectionHeading eyebrow="Mini caso empresarial" title="NOVA S.A.C." aside="Empresa comercial multicanal · Caso educativo · Datos simulados"/><p className="mt-5 max-w-3xl text-lg text-muted-foreground">NOVA está creciendo, pero también aumentan sus problemas operativos.</p><div className="mt-7 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{["Aumento de reclamos","Falta de stock","Retrasos","Muchos correos","Reportes manuales","Archivos dispersos"].map(x=><div className="metric" key={x}>{x}</div>)}</div><div className="mt-10 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="glass-panel"><h3 className="text-xl font-bold">Si fueras responsable de NOVA, ¿dónde implementarías IA primero?</h3><div className="mt-5 grid gap-2">{novaItems.map(n=><button onClick={()=>setChoice(n.name)} className={`option ${choice===n.name?"selected":""}`} key={n.name}>{n.name}</button>)}</div>{choice&&<div className="mt-4 rounded-lg border border-accent/40 bg-accent/10 p-4 text-sm"><strong>Buena hipótesis.</strong> Ahora debemos analizar impacto, viabilidad, datos disponibles y riesgo antes de decidir.<Button className="mt-4 w-full" onClick={()=>setMatrix(true)}>Llevar a la matriz</Button></div>}</div><div className="glass-panel"><div className="flex justify-between gap-2"><h3 className="text-xl font-bold uppercase">Matriz de priorización</h3><span className="eyebrow">Impacto × facilidad</span></div><div className="matrix mt-6"><span className="axis-y">Impacto empresarial</span><div className="quadrant q1">Alto impacto<br/>difícil</div><div className="quadrant q2">Alto impacto<br/>fácil</div><div className="quadrant q3">Bajo impacto<br/>difícil</div><div className="quadrant q4">Bajo impacto<br/>fácil</div>{matrix&&novaItems.map(n=><button title={`${n.name}: ejemplo didáctico`} key={n.name} className={`matrix-dot ${choice===n.name?"chosen":""}`} style={{left:`calc(${n.x}% - 12px)`,bottom:`calc(${n.y}% - 12px)`}}>{n.name.slice(0,2)}</button>)}</div><p className="mt-3 text-center text-xs text-muted-foreground">Facilidad de implementación →</p><p className="mt-5 text-sm text-muted-foreground">Alto impacto + fácil implementación puede ser una zona razonable para explorar oportunidades iniciales; no es una regla absoluta.</p></div></div></div></section>}

function HumanAI(){return <section className="shell py-20"><SectionHeading eyebrow="Colaboración" title="IA + criterio humano" aside="La responsabilidad final sigue requiriendo personas."/><div className="mt-8 grid gap-3 md:grid-cols-[1fr_auto_1fr]"><Role title="IA" accent items={["Procesa grandes cantidades de información","Encuentra patrones","Clasifica","Resume","Genera contenido","Propone alternativas"]}/><div className="collaboration"><span>+</span><strong>Colaboración</strong></div><Role title="Persona" items={["Define objetivos","Comprende el contexto","Valida resultados","Considera consecuencias","Toma responsabilidad","Decide"]}/></div><p className="mx-auto mt-8 max-w-3xl text-center text-xl font-semibold">La calidad de una solución empresarial con IA depende tanto de la tecnología como del criterio con el que se utiliza.</p></section>}
function Role({title,items,accent=false}:{title:string;items:string[];accent?:boolean}){return <div className={`glass-panel ${accent?"border-accent/40":"border-amber/40"}`}><h3 className={`text-2xl font-bold uppercase ${accent?"text-accent":"text-amber"}`}>{title}</h3><ul className="mt-5 grid gap-3">{items.map(x=><li className="flex items-center gap-3" key={x}><span className={`size-1.5 rounded-full ${accent?"bg-accent":"bg-amber"}`}/>{x}</li>)}</ul></div>}

function Risks(){return <section className="band"><div className="shell"><SectionHeading eyebrow="Uso responsable" title="Riesgos y limitaciones" aside="Abre cada riesgo para revisar cómo reducirlo."/><div className="mt-8 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{risks.map(r=><RiskCard key={r[0]} title={r[0]} description={r[1]} solution={r[2]}/>)}</div></div></section>}

const questions=["¿Cuál es el problema?","¿Qué información existe?","¿Cómo podría apoyar la IA?","¿Qué resultado esperarías?","¿Quién debería validar el resultado?","¿Qué KPI utilizarías para medir el impacto?"];
function FinalChallenge(){const [topic,setTopic]=useState("Ventas");const [answers,setAnswers]=useState(Array(6).fill(""));const complete=answers.every(Boolean);const reset=()=>setAnswers(Array(6).fill(""));return <section id="reto" className="shell py-20"><SectionHeading eyebrow="Reto final" title="Tu primer reto como gestor de IA" aside="Formula una hipótesis empresarial completa. Nada se guarda fuera de esta página."/><div className="mt-8 flex flex-wrap gap-2">{["Ventas","Inventarios","Atención al cliente","Operaciones","Recursos humanos","Finanzas"].map(x=><Button key={x} variant={topic===x?"default":"outline"} onClick={()=>setTopic(x)}>{x}</Button>)}</div><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_.8fr]"><form className="glass-panel" onSubmit={e=>e.preventDefault()}><span className="eyebrow">Área seleccionada · {topic}</span><div className="mt-5 grid gap-4">{questions.map((q,i)=><label key={q} className="grid gap-2 text-sm font-semibold">{i+1}. {q}<textarea rows={2} value={answers[i]} onChange={e=>setAnswers(a=>a.map((x,j)=>j===i?e.target.value:x))} className="field" placeholder="Escribe una respuesta breve..."/></label>)}</div><div className="mt-5"><ResetButton onClick={reset}/></div></form><aside className="glass-panel h-fit lg:sticky lg:top-28"><span className="eyebrow">Tu mapa de valor</span><div className="mt-5 grid gap-2">{["Problema","Información","IA","Resultado","Decisión","KPI"].map((x,i)=><div key={x} className={`challenge-step ${answers[i]?"filled":""}`}><span>{x}</span><p>{answers[i]||"Pendiente"}</p>{i<5&&<ArrowDown/>}</div>)}</div>{complete&&<div className="mt-5 flex items-center gap-3 rounded-lg bg-accent/10 p-4 text-sm text-accent"><ShieldCheck/>Hipótesis completa: ahora debe validarse con datos y personas.</div>}</aside></div></section>}

function Roadmap(){return <section id="ruta" className="band"><div className="shell"><SectionHeading eyebrow="Cierre y ruta del curso" title="Hoy descubriste dónde puede generar valor la IA" aside="Durante el curso aprenderás cómo construir esas soluciones."/><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{courseRoute.map((x,i)=><div className={`roadmap-item ${i===0?"current":""}`} key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div><div className="mt-12 border-l-2 border-accent pl-5"><p className="eyebrow">Pregunta final</p><p className="mt-2 max-w-3xl text-2xl font-semibold">Si mañana tuvieras que implementar IA en una empresa, ¿qué proceso analizarías primero y por qué?</p></div></div></section>}

function Footer(){return <footer className="relative z-10 border-t border-line bg-background/80"><div className="shell flex flex-wrap justify-between gap-3 py-6 font-mono text-[10px] uppercase tracking-widest text-muted-foreground"><span>AI Business Explorer · Masterclass</span><span>La decisión y responsabilidad final siguen siendo humanas</span></div></footer>}